USE [master]
GO

/****** Object:  Database [REDEMPTION]    Script Date: 2/11/2019 10:47:22 AM ******/
CREATE DATABASE [REDEMPTION]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'REDEMPTION', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\REDEMPTION.mdf' , SIZE = 3264KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'REDEMPTION_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\REDEMPTION_log.ldf' , SIZE = 832KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [REDEMPTION] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [REDEMPTION].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [REDEMPTION] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [REDEMPTION] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [REDEMPTION] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [REDEMPTION] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [REDEMPTION] SET ARITHABORT OFF 
GO

ALTER DATABASE [REDEMPTION] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [REDEMPTION] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [REDEMPTION] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [REDEMPTION] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [REDEMPTION] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [REDEMPTION] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [REDEMPTION] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [REDEMPTION] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [REDEMPTION] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [REDEMPTION] SET  ENABLE_BROKER 
GO

ALTER DATABASE [REDEMPTION] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [REDEMPTION] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [REDEMPTION] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [REDEMPTION] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [REDEMPTION] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [REDEMPTION] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [REDEMPTION] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [REDEMPTION] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [REDEMPTION] SET  MULTI_USER 
GO

ALTER DATABASE [REDEMPTION] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [REDEMPTION] SET DB_CHAINING OFF 
GO

ALTER DATABASE [REDEMPTION] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [REDEMPTION] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [REDEMPTION] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [REDEMPTION] SET  READ_WRITE 
GO


