USE [master]
GO

/****** Object:  Database [SessionMgmntDb]    Script Date: 2/8/2019 5:03:33 PM ******/
CREATE DATABASE [SessionMgmntDb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SessionMgmntDb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\SessionMgmntDb.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'SessionMgmntDb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\SessionMgmntDb_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [SessionMgmntDb] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SessionMgmntDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SessionMgmntDb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SessionMgmntDb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SessionMgmntDb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SessionMgmntDb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SessionMgmntDb] SET ARITHABORT OFF 
GO

ALTER DATABASE [SessionMgmntDb] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [SessionMgmntDb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SessionMgmntDb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SessionMgmntDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SessionMgmntDb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SessionMgmntDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SessionMgmntDb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SessionMgmntDb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SessionMgmntDb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SessionMgmntDb] SET  DISABLE_BROKER 
GO

ALTER DATABASE [SessionMgmntDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SessionMgmntDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SessionMgmntDb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SessionMgmntDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SessionMgmntDb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SessionMgmntDb] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SessionMgmntDb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SessionMgmntDb] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [SessionMgmntDb] SET  MULTI_USER 
GO

ALTER DATABASE [SessionMgmntDb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SessionMgmntDb] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SessionMgmntDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SessionMgmntDb] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [SessionMgmntDb] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [SessionMgmntDb] SET  READ_WRITE 
GO


